route_name_to_api_name:
  auth.login: LOGIN
  auth.logout: LOGOUT
  auth.refresh: REFRESH ACCESS TOKEN
  auth.token.expiration: TOKEN EXPIRATION
  password.forgot: FORGOT PASSWORD
  password.reset: RESET PASSWORD
  user.list: USER LIST
  user.detail: USER DETAIL
  user.create: USER CREATE
  user.update: USER UPDATE
  user.delete: USER DELETE
  role.list: ROLE LIST
  role.detail: ROLE DETAIL
  role.create: ROLE CREATE
  role.update: ROLE UPDATE
  role.delete: ROLE DELETE
  event.type.list: EVENT TYPE LIST
  event.type.detail: EVENT TYPE DETAIL
  event.type.create: EVENT TYPE CREATE
  event.type.update: EVENT TYPE UPDATE
  event.type.delete: EVENT TYPE DELETE
  event.type.import.csv: EVENT TYPE IMPORT CSV
  event.type.export.csv: EVENT TYPE EXPORT CSV
